### ISSUE TITLE
Ruby Speech sample and client library use "RAW" as an encoding instead of "LINEAR16"

### ISSUE THREAD

**Issue by danaharon** [GoogleCloudPlatform/ruby-docs-samples#166]
There are many ways to encode files e.g., LINEAR16, Mulaw and then there are different file formats that encapsulate them e.g., RAW and WAV.
Both RAW and WAV can encapsulate both LINEAR16 and Mulaw.
For our server - we don't need to know the file format - we only need to know the encoding e.g., using the term RAW to specify an encoding is an error.

**Comment by sgreenberg** [comment]
https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/168 addresses this.

**Comment by remi** [comment]
Thanks @danaharon!

The `:raw` value used by the Ruby Speech client as an [alias](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/52b512b09ac5070a6c038f058793ecaa1f1267fe/google-cloud-speech/lib/google/cloud/speech/project.rb#L625-L630) for LINEAR16.

`:raw`, `:linear`, and `:linear16` are all acceptable values.

We will update the sample to use `:linear16` for clarity and have started [a thread](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1426) on the Speech client library proposing the possible removal of :raw due to this confusion!

**Comment by remi** [comment]
The change will also be made in the library, removing `:raw` altogether IIUC

https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1428
