### ISSUE TITLE
Main README should display links to all samples in this repository

### ISSUE THREAD

**Issue by beccasaurus** [GoogleCloudPlatform/ruby-docs-samples#69]

**Comment by remi** [comment]
See draft branch: [`update-READMEs`](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/update-READMEs)

**Comment by grant** [comment]
Client libraries don't link the samples in the READMEs as they are hard to maintain.

This feature request is not consistent with other client libraries. A larger effort would be needed if we want to change the style of our READMEs.

The draft branch doesn't exist anymore and there's no description to this issue. Closing due to age and WAI.
