### ISSUE TITLE
Cannot insert legacy ACL for an object when uniform bucket-level access is enabled

### ISSUE THREAD

**Issue by IanVaughan** [GoogleCloudPlatform/ruby-docs-samples#888]
Following https://cloud.google.com/ruby/getting-started
When attempting to save an image to a book.
The following error is logged:
```
Google::Cloud::InvalidArgumentError: invalid: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access
	/layers/google.ruby.bundle/gems/.bundle/gems/ruby/2.5.0/gems/google-cloud-storage-1.34.1/lib/google/cloud/storage/service.rb:763:in `rescue in execute'
	/layers/google.ruby.bundle/gems/.bundle/gems/ruby/2.5.0/gems/google-cloud-storage-1.34.1/lib/google/cloud/storage/service.rb:760:in `execute'
	/layers/google.ruby.bundle/gems/.bundle/gems/ruby/2.5.0/gems/google-cloud-storage-1.34.1/lib/google/cloud/storage/service.rb:350:in `insert_file'
	/layers/google.ruby.bundle/gems/.bundle/gems/ruby/2.5.0/gems/google-cloud-storage-1.34.1/lib/google/cloud/storage/bucket.rb:1515:in `create_file'
	/workspace/app/models/book.rb:141:in `upload_image'
	/workspace/app/models/book.rb:137:in `update_image'
	/workspace/app/models/book.rb:131:in `update'
	/workspace/app/controllers/books_controller.rb:44:in `update'
```

**Comment by dazuma** [comment]
The code may be attempting to set an ACL directly. Need to investigate.

**Comment by NivedhaSenthil** [comment]
yes this is happening because we are setting acl as public for the file being uploaded here https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/3e0deb9c360112109919c59aa2ba43b7749ad084/getting-started/bookshelf/app/models/book.rb#L152
 either the bucket can be created with fine-grained access to allow setting acls for individual objects 
<img width="528" alt="Screen Shot 2022-01-04 at 2 39 56 PM" src="https://user-images.githubusercontent.com/6358540/148036158-12149251-649a-4658-baef-da87cc072abf.png">

or the sample can be modified to remove the explicit acl setting. 
Closing this issue for now, please feel free to reopen if you have any further questions.
